class/config/routes.rb
Rails.application.routes.draw do
  root 'users#index', defaults: {format: :json}
  get '/users/:user_id/invitations', to: 'invitations#indexbyuser', defaults: {format: :json}
  get '/users/deleteall', to: 'users#destroyAll', defaults: {format: :json}    ## DELETE ALL USERS
  get '/users/createbulk/:count', to: 'users#createBulk', defaults: {format: :json}    ## CREATE A LOT OF USER

  get '/events/:event_id/invitations', to: 'invitations#indexbyevent', defaults: {format: :json}
  resources :users, defaults: {format: :json} do
    resources :invitations, shallow:true, except: ['new', 'create','index'], defaults: {format: :json}
    resources :events, shallow:true, defaults: {format: :json} do
        resources :invitations, shallow:true, except:['index'], defaults: {format: :json}
        resources :comments, shallow:true, defaults: {format: :json}

    end
  end
  #resources :invitations
  #resources :events
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

class/app/models/event.rb
class Event < ApplicationRecord
  connects_to database:{
    writing: primary,
    reading: primay_replica
  }
  
  belongs_to :user
  has_many :invitations, dependent: :destroy
  has_many :comments
  
  validates :name, :location, :start_time, :end_time, presence: true
  
end

class/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    begin
      @user = User.find(params[:user_id])
      @events = @user.events.all
    rescue
      head 403
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
     @event = Event.find(params[:id])
     @user = User.find(@event.user_id)
  end

  # GET /events/new
  def new
    begin
      @user = User.find(params[:user_id])
    rescue
      head 403
    end
    @event = @user.events.new
  end

  # GET /events/1/edit
  def edit
    #@user = User.find(params[:user_id])
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @user = User.find(params[:user_id])
    @event = @user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to user_events_path(@user), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    begin
      @event = Event.find(params[:id]);
    rescue 
      head 403
    end
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to user_events_path(@user), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    begin
      @event = Event.find(params[:id]);
      @event.destroy
      status 200
    rescue
      head 200
    end
    respond_to do |format|
      format.html { redirect_to user_events_url, notice: 'Event was successfully destroyed.' }
      format.json {head :ok}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def set_event
    end
    def event_params
      params.require(:event).permit(:name, :description, :location, :start_time, :end_time, :user_id)
    end
  end

class/app/helpers/events_helper.rb
module EventsHelper
end

class/app/views/events/_form.html.erb
<%= form_with(model: [user, event], local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

class/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', user: @user, event: @event %>

<%= link_to 'Show', user_event_path(@user,@event) %> |
<%= link_to 'Back', user_events_path %>

class/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Start time</th>
      <th>End time</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.location %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= event.user_id %></td>
        <td><%= link_to 'Show', user_event_path(@user,event) %></td>
        <td><%= link_to 'Edit', edit_user_event_path(@user,event) %></td>
        <td><%= link_to 'Destroy', user_event_path(@user,event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_user_event_path(@user) %><br><br>
<%= link_to 'Back to user details', user_path(@user) %>

class/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', user: @user, event: @user.events.build %>

<%= link_to 'Back', user_events_path %>

class/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user_id %>
</p>
<%= link_to 'See invitations for this event', user_event_invitations_path(@user,@event) %> <br><br>
<%= link_to 'Edit', edit_user_event_path(@event.user_id,@event) %> |
<%= link_to 'Back', user_events_path %>