class/config/routes.rb
Rails.application.routes.draw do
  root 'users#index', defaults: {format: :json}
  get '/users/:user_id/invitations', to: 'invitations#indexbyuser', defaults: {format: :json}
  get '/users/deleteall', to: 'users#destroyAll', defaults: {format: :json}    ## DELETE ALL USERS
  get '/users/createbulk/:count', to: 'users#createBulk', defaults: {format: :json}    ## CREATE A LOT OF USER

  get '/events/:event_id/invitations', to: 'invitations#indexbyevent', defaults: {format: :json}
  resources :users, defaults: {format: :json} do
    resources :invitations, shallow:true, except: ['new', 'create','index'], defaults: {format: :json}
    resources :events, shallow:true, defaults: {format: :json} do
        resources :invitations, shallow:true, except:['index'], defaults: {format: :json}
        resources :comments, shallow:true, defaults: {format: :json}

    end
  end
  #resources :invitations
  #resources :events
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

class/app/models/invitation.rb
class Invitation < ApplicationRecord
  connects_to database:{
    writing: primary,
    reading: primay_replica
  }
  
  belongs_to :user
  belongs_to :event
  
  enum response: [:no_response, :yes, :no, :maybe]
end

class/app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: [:show, :edit, :update]

  # GET /users/1/invitations
  # GET /users/1/invitations.json
  def indexbyuser
    begin
      @event_ids = []
      @user = User.find(params[:user_id])
      @invitations = Invitation.joins(:event).where(invitations: { user_id: params[:user_id] })
      for @invitation in @invitations
        @event_ids << @invitation.event_id
      end
      @events = Event.find(@event_ids)
      rescue
        head 403
    end
  end
  
  # GET /events/1/invitations
  # GET /events/1/invitations.json
  def indexbyevent
    begin
    @user_ids = []
    @event = Event.find(params[:event_id])
    @invitations = Invitation.joins(:user).where(invitations: { event_id: params[:event_id] })
    for @invitation in @invitations
      @user_ids << @invitation.user_id
    end
    @users = User.find(@user_ids)
    rescue
      head 403
    end

  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    begin
      @event = Event.find(params[:event_id])
    rescue
      head 403
    end
    @invitation = @event.invitations.new
  end

  # GET /invitations/1/edit
  def edit
  end

  # POST /invitations
  # POST /invitations.json
  def create
    begin
      @event = Event.find(params[:event_id])
    rescue
      head 403
    end
    print "invitaion_params print: "
    print invitation_params
    @invitation = @event.invitations.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to user_event_invitations_path(@user,@event), notice: 'Invitation was successfully created.' }
        format.json { render :show, status: :created, location: @invitation }
      else
        format.html { render :new }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1
  # PATCH/PUT /invitations/1.json
  def update
    begin
      @invitation = Invitation.find(params[:id]);
    rescue
      head 403
    end
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    begin
      @invitation = Invitation.find(params[:id]);
    rescue
      head 200
    end
    if( @invitation != nil)
      @invitation.destroy
    end
    respond_to do |format|
      format.html { redirect_to user_event_invitations_url, notice: 'Invitation was successfully destroyed.' }
      format.json { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      begin
        @invitation = Invitation.find(params[:id])
      rescue
        head 403
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invitation_params
      params.require(:invitation).permit(:user_id, :event_id, :response)
    end
end

class/app/helpers/invitations_helper.rb
module InvitationsHelper
end

class/app/views/invitations/_form.html.erb
<%= form_with(model: [user, event, invitation], local: true) do |form| %>
  <% if invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
        <% invitation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.number_field :event_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

class/app/views/invitations/edit.html.erb
<h1>Editing Invitation</h1>

<%= render 'form', user: @user, event: @event, invitation: @invitation %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', user_event_invitations_path(@invitation.event.user, @invitation.event) %>

class/app/views/invitations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invitations</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Invited User</th>
      <th>Response</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
        <td><%= invitation.user_id %></td>
        <td><%= invitation.event_id %></td>
        <td><%= invitation.response %></td>
        <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitation', new_user_event_invitation_path %> <br><br>

<%= link_to 'Back to event', user_event_path(@user,@event) %>

class/app/views/invitations/new.html.erb
<h1>New Invitation</h1>

<%= render 'form', user: @user, event: @event, invitation: @event.invitations.build %>

<%= link_to 'Back', user_event_invitations_path %>

class/app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @invitation.event_id %>
</p>


<p>
  <strong>Invited User:</strong>
  <%= @invitation.user_id %>
</p>


<p>
  <strong>Response:</strong>
  <%= @invitation.response %>
</p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', user_event_invitations_path(@invitation.event.user, @invitation.event) %>